### ISSUE TITLE
Run code formatter on code base

### ISSUE THREAD

**Issue by salto-edit** [ltworf/ltdata#10]
The author of LtData recently added PEP8 conformance to the styleguide of the project and already the main file has a bunch of errors:

> W291:6:2:trailing whitespace
> W291:11:2:trailing whitespace
> W291:16:2:trailing whitespace
> W291:19:2:trailing whitespace
> E265:26:1:block comment should start with '# '
> E225:30:13:missing whitespace around operator
> E261:30:16:at least two spaces before inline comment
> E262:30:17:inline comment should start with '# '
> E225:31:7:missing whitespace around operator
> E302:33:1:expected 2 blank lines, found 1
> E211:33:12:whitespace before '('
> E231:33:18:missing whitespace after ','
> E231:33:23:missing whitespace after ','
> E201:35:18:whitespace after '('
> E228:35:39:missing whitespace around modulo operator
> E231:35:45:missing whitespace after ','
> E202:35:51:whitespace before ')'
> E302:38:1:expected 2 blank lines, found 1
> E211:38:10:whitespace before '('
> E231:38:18:missing whitespace after ','
> E231:38:24:missing whitespace after ','
> E231:38:29:missing whitespace after ','
> E225:42:10:missing whitespace around operator
> E231:42:27:missing whitespace after ','
> E231:42:33:missing whitespace after ','
> E231:43:24:missing whitespace after ','
> E225:46:13:missing whitespace around operator
> E711:46:13:comparison to None should be 'if cond is not None:'
> E265:47:13:block comment should start with '# '
> E225:49:22:missing whitespace around operator
> E203:50:29:whitespace before ','
> E231:52:29:missing whitespace after ','
> E231:52:35:missing whitespace after ','
> E302:55:1:expected 2 blank lines, found 1
> E211:55:9:whitespace before '('
> E211:59:30:whitespace before '('
> E201:59:32:whitespace after '('
> E202:59:50:whitespace before ')'
> E302:61:1:expected 2 blank lines, found 1
> E231:61:15:missing whitespace after ','
> E225:62:6:missing whitespace around operator
> E231:62:19:missing whitespace after ','
> E225:63:6:missing whitespace around operator
> E225:65:10:missing whitespace around operator
> E231:65:25:missing whitespace after ','
> E302:68:1:expected 2 blank lines, found 1
> E261:75:51:at least two spaces before inline comment
> E262:75:52:inline comment should start with '# '
> E501:75:80:line too long (91 > 79 characters)
> E231:78:43:missing whitespace after ','
> E261:78:58:at least two spaces before inline comment
> E262:78:59:inline comment should start with '# '
> E225:80:26:missing whitespace around operator
> E302:82:1:expected 2 blank lines, found 1
> E231:82:22:missing whitespace after ','
> E211:85:25:whitespace before '('
> W293:91:1:blank line contains whitespace
> E225:96:12:missing whitespace around operator
> E225:97:19:missing whitespace around operator
> E225:98:21:missing whitespace around operator
> E225:99:17:missing whitespace around operator
> E261:101:33:at least two spaces before inline comment
> E262:101:34:inline comment should start with '# '
> W293:102:1:blank line contains whitespace
> E302:103:1:expected 2 blank lines, found 1
> E231:103:21:missing whitespace after ','
> E211:104:14:whitespace before '('
> E201:104:16:whitespace after '('
> E202:104:41:whitespace before ')'
> E211:105:14:whitespace before '('
> E201:105:16:whitespace after '('
> E501:105:80:line too long (91 > 79 characters)
> E202:105:90:whitespace before ')'
> E225:106:9:missing whitespace around operator
> E231:106:27:missing whitespace after ','
> W293:107:1:blank line contains whitespace
> E302:108:1:expected 2 blank lines, found 1
> W293:109:1:blank line contains whitespace
> E211:110:25:whitespace before '('
> E201:110:27:whitespace after '('
> E202:110:62:whitespace before ')'
> E211:111:17:whitespace before '('
> E201:111:19:whitespace after '('
> E201:111:21:whitespace after '('
> E202:111:55:whitespace before ')'
> E202:111:57:whitespace before ')'
> E225:112:21:missing whitespace around operator
> W293:113:1:blank line contains whitespace
> E265:114:5:block comment should start with '# '
> W293:116:1:blank line contains whitespace
> E225:117:9:missing whitespace around operator
> E231:117:27:missing whitespace after ','
> E265:118:5:block comment should start with '# '
> W293:119:1:blank line contains whitespace
> E231:120:21:missing whitespace after ','
> E231:125:21:missing whitespace after ','
> E231:125:23:missing whitespace after ','
> E211:128:25:whitespace before '('
> E201:128:27:whitespace after '('
> E202:128:32:whitespace before ')'
> W293:129:1:blank line contains whitespace
> E225:130:21:missing whitespace around operator
> E261:130:25:at least two spaces before inline comment
> E262:130:26:inline comment should start with '# '
> W293:132:1:blank line contains whitespace
> E211:133:21:whitespace before '('
> E201:133:23:whitespace after '('
> E202:133:30:whitespace before ')'
> E231:134:30:missing whitespace after ','
> E211:134:54:whitespace before '['
> E201:134:56:whitespace after '['
> E202:134:58:whitespace before ']'
> E211:135:22:whitespace before '('
> E201:135:24:whitespace after '('
> E211:135:47:whitespace before '['
> E201:135:49:whitespace after '['
> E202:135:51:whitespace before ']'
> E202:135:62:whitespace before ')'
> E211:136:23:whitespace before '('
> E201:136:25:whitespace after '('
> E202:136:35:whitespace before ')'
> E211:137:30:whitespace before '('
> E201:137:32:whitespace after '('
> E202:137:36:whitespace before ')'
> E211:137:38:whitespace before '['
> E201:137:40:whitespace after '['
> E202:137:42:whitespace before ']'
> E211:137:52:whitespace before '('
> E201:137:54:whitespace after '('
> E202:137:62:whitespace before ')'
> E211:138:31:whitespace before '('
> E201:138:33:whitespace after '('
> E211:138:44:whitespace before '('
> E201:138:46:whitespace after '('
> E202:138:50:whitespace before ')'
> E211:138:52:whitespace before '['
> E201:138:54:whitespace after '['
> E202:138:57:whitespace before ']'
> E202:138:59:whitespace before ')'
> E211:140:38:whitespace before '('
> E201:140:40:whitespace after '('
> E211:140:51:whitespace before '('
> E201:140:53:whitespace after '('
> E202:140:57:whitespace before ')'
> E211:140:59:whitespace before '['
> E201:140:61:whitespace after '['
> E202:140:64:whitespace before ']'
> E202:140:66:whitespace before ')'
> E211:140:74:whitespace before '('
> E201:140:76:whitespace after '('
> E202:140:80:whitespace before ')'
> E501:140:80:line too long (88 > 79 characters)
> E211:140:82:whitespace before '['
> E201:140:84:whitespace after '['
> E202:140:87:whitespace before ']'
> E231:144:23:missing whitespace after ','
> E231:144:35:missing whitespace after ','
> E231:144:43:missing whitespace after ','
> E225:146:12:missing whitespace around operator
> W293:149:1:blank line contains whitespace

**Comment by ltworf** [comment]
I said that the formatter should be run before a commit, not that it is okay to spend hours o fix the things that the formatter doesn't fix.

Closing.

**Comment by salto-edit** [comment]
:-1:
